#  <-- tasks file can include smaller files if warranted
---
# file: roles/common/tasks/main.yml
- name: Set IPS
  fail:
    msg: "Error to set IP you must specify for the same interface ansible_host_tmp or an ip for a children connection"
  loop: "{{ connections }}"
  loop_control:
    loop_var: connection
  when: "{{ not (connection.ip|d(False) or ansible_host_tmp|d(False)) }}"
- name: Set IPS
  include: setIP.yml
  loop: "{{ connections }}"
  loop_control:
    loop_var: connection