---
collections:
  # - crivetimihai.virtualization
  # - inverse_inc.windows
  - pfsensible.core
  # - gantsign.kompose
  - linux-system-roles.network #EL like
  # - mrlesmithjr.netplan #ubuntu (not working)
  # - andrewrothstein.docker-compose