---
collections:
  ## SetIP
  - pfsensible.core
  # - linux-system-roles.network #EL like

  ## firewall

  ## AD 
  - amtega.win_domain_ous #OrganizationalUnits

  - freeipa.ansible_freeipa

  - scicore.guacamole

  # - crivetimihai.virtualization
  # - inverse_inc.windows
  # - gantsign.kompose
  # - mrlesmithjr.netplan #ubuntu (not working)
  # - andrewrothstein.docker-compose