---
collections:
  ## SetIP
  - pfsensible.core
  - linux-system-roles.network #EL like

  ## firewall
  - pfsensible.core

  ## AD 
  - amtega.win_domain_ous #OrganizationalUnits

  # - crivetimihai.virtualization
  # - inverse_inc.windows
  # - gantsign.kompose
  # - mrlesmithjr.netplan #ubuntu (not working)
  # - andrewrothstein.docker-compose