#  <-- tasks file can include smaller files if warranted
---
# file: roles/common/tasks/main.yml

- name: linux block
  block:
    - name: debug
      debug:
        var: ansible_facts['distribution']
    - name: redhat | Centos
      get_url:
        url: https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh
        dest: /tmp/td-agent.sh
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'CentOS'
    - name: ubuntu
      block:
        - name: ubuntu16
          get_url:
            url: https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh
            dest: /tmp/td-agent.sh
          when: ansible_distribution_version == "16.04"
        - name: ubuntu18
          get_url:
            url: https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent3.sh
            dest: /tmp/td-agent.sh
          when: ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"
        # - name: ubuntu20
        #   when: ansible_distribution_version == "20.04"
      when: ansible_facts['distribution'] == 'Ubuntu'
    - name: debian
      block:
        - name: debian9
          get_url:
            url: https://toolbelt.treasuredata.com/sh/install-debian-stretch-td-agent3.sh
            dest: /tmp/td-agent.sh
          when: ansible_distribution_version == "9"
        - name: debian10
          get_url:
            url: https://toolbelt.treasuredata.com/sh/install-debian-buster-td-agent3.sh
            dest: /tmp/td-agent.sh
          when: ansible_distribution_version == "10"
      when: ansible_facts['distribution'] == 'Debian'
    - name: Install fluentd
      shell: sh /tmp/td-agent.sh
      register: out
      become: yes
      become_user: root
    # - name: redo install
    #   block:
    #     - name: sleep
    #       pause:
    #         seconds: 40
    #     - name: Install fluentd
    #       shell: sh /tmp/td-agent.sh
    #       register: out
    #       become: yes
    #       become_user: root
    #   when: "'Installation incompleted. Check above messages.' in out.stdout_lines"
    # - name: debug
    #   debug:
    #     var: out
    - name: fail installation
      fail:
        msg: Error while installing fluentd
      when: "'Installation incompleted. Check above messages.' in out.stdout_lines|d(False)"
    - name: Remove fluentd install fluentd
      shell: rm /tmp/td-agent.sh
  when: ansible_facts['os_family'] != 'Windows'
- name: windows installation
  win_fluentd_install:
    version: 3.7.1-0
  register: out
  when: ansible_facts['os_family'] == 'Windows'
# - name: debug
#   debug:
#     var: out