#  <-- tasks file can include smaller files if warranted
---
# file: roles/common/tasks/main.yml
# - name: Windows PKI
#   include: winADDS.yml
#   when: "ansible_facts['os_family'] == 'Windows' and 'CA' in group_names"
- name: Deploy root CA for windows
  include: deployWindows.yml
  when: ansible_facts['os_family'] == 'Windows'