---
# firewall_group_rules:
#   - name: 'Allow Internal HTTPS traffic'
#     action: pass
#     interface: lan
#     ipprotocol: inet
#     protocol: udp
#     source: dns_int
#     destination: any
#     destination_port: 53
#     after: 'Allow proxies out'
#     state: present