ansible_host: 192.168.29.183

ansible_host_tmp: 192.168.29.183

hostname: ad-master

interfaces:
  - name: Ethernet0
    gateway: 192.168.29.2

AD_users:
  - users_variable

users_variable:
  # - name: OUBase
  - name: testU
    surname: testtttt
    city: washington
    groups:
     - testGroup
    mail: test@mail.com
    OU: test1

AD_groups:
  - groups_variable

groups_variable:
  # - name: OUBase
  - name: testGroup
    OU: test1
  - name: testGroupBase
    # OU: test1

AD_OUs:
  - OUs_variable
OUs_variable:
  # - name: OUBase
  - name: OUInsideBase
    parent: test1
  - name: OUInsideBase2
    parent: OUInsideBase
  #   parents:
  #     - OUBase
  # - name: OUInsideInsideBase
  #   parents:
  #     - OUInsideBase
  #     - OUBase

shares:
  - name: testingininignini
    namespace: testnamspacestest
    # host: ad-master
    type: dfs
    path: C:\sharing
    # owner: Administrator

folders:
  - path: 'C:\testing1\testing'
    owner:
      name: Administrator
      recurse: true
    # owner: Administrator
    acls:
      - user: Users #Domain User
        state: present
        inherit: ContainerInherit
        propagation: InheritOnly 
        rights: Read
files:
  - sourceLocal: ../../inventories/files/test.zip
    destination: C:/testing1/testing/testfolder
    uncompress: true
    owner:
      name: Administrator
      recurse: true
    # owner: Administrator
    acls:
      - user: Users
        state: present
        inherit: ContainerInherit
        propagation: InheritOnly 
        rights: Read