# - name: Uninstall feature if present
#   win_wipe_AD:
#      localAdminPassword: "{{ ansible_password }}"
#   register: out
# - name: Wait for server to be up after uninstall
#   wait_for_connection:
#     delay: 120
#     timeout: 180
#   when: out.changed
# - name: install ad
#   win_feature:
#     name: AD-Domain-Services
#     include_management_tools: yes
#     include_sub_features: yes
#     state: present
#   register: result
# - name: Create new domain in a new forest on the target host
#   win_domain:
#     dns_domain_name: "{{ domain.name }}"
#     safe_mode_password: "{{ domain.recoveryPassword if domain.recoveryPassword|d(False) else ansible_password }}"
#   register: ad0
# - name: Create new domain in a new forest with specific parameters
#   win_domain:
#     create_dns_delegation: no
#     database_path: C:\Windows\NTDS
#     dns_domain_name: "{{ domain.name }}"
#     domain_mode: Win2012R2
#     domain_netbios_name: ANSIBLE
#     forest_mode: Win2012R2
#     safe_mode_password: password123!
#     sysvol_path: C:\Windows\SYSVOL
#   register: ad1
# - name: reboot server
#   win_reboot:
#     msg: "Installing AD. Rebooting..."
#   when: ad0.changed or ad1.changed
# - name: Wait for server to be up after install
#   wait_for_connection:
#     delay: 300
#     timeout: 500
#   when: ad0.changed or ad1.changed

- name: Prepare Organizational Units variable
  block:
    - set_fact:
        AD_OUs_to_set: "{{ AD_OUs }}"
      when: AD_OUs[0] is mapping
    - set_fact:
        AD_OUs_to_set: "{{ AD_OUs_to_set|d([]) + lookup('vars', alias)|d([]) }}"
      loop: "{{ AD_OUs  }}"
      loop_control:
        loop_var: alias
      when: AD_OUs[0] is string
  when: AD_OUs|d([])|length>0

- name: Create OU
  include: OU.yml
  loop: "{{ AD_OUs_to_set }}"
  loop_control:
    loop_var: OU
  when: AD_OUs_to_set|d(False)



- name: Prepare Groups variable
  block:
    - set_fact:
        AD_groups_to_set: "{{ AD_groups }}"
      when: AD_groups[0] is mapping
    - set_fact:
        AD_groups_to_set: "{{ AD_groups_to_set|d([]) + lookup('vars', alias)|d([]) }}"
      loop: "{{ AD_groups }}"
      loop_control:
        loop_var: alias
      when: AD_groups[0] is string
  when: AD_groups|d([])|length>0

- name: Create AD_group
  include: group.yml
  loop: "{{ AD_groups_to_set }}"
  loop_control:
    loop_var: AD_group
  when: AD_groups_to_set|d(False)

- name: Prepare Users variable
  block:
    - set_fact:
        AD_users_to_set: "{{ AD_users }}"
      when: AD_users[0] is mapping
    - set_fact:
        AD_users_to_set: "{{ AD_users_to_set|d([]) + lookup('vars', alias)|d([]) }}"
      loop: "{{ AD_users }}"
      loop_control:
        loop_var: alias
      when: AD_users[0] is string
  when: AD_users|d([])|length>0

- name: Create AD_user
  include: user.yml
  loop: "{{ AD_users_to_set }}"
  loop_control:
    loop_var: AD_user
  when: AD_users_to_set|d(False)