- set_fact:
    OU_ldap_path: "{{ False }}"
- name: Get OU parent
  include: subTask/getOUPath.yml
  vars:
    OU_name: "{{ OU.parent }}"
    domain_name_var: "{{ domain.name }}"
  when: OU.parent|d(False)
- include_role:
    name: amtega.win_domain_ous
  vars:
    win_domain_ous_no_log: false
    win_domain_ous:
      - name: "{{ OU.name }}"
        path: "{{ OU_ldap_path if OU_ldap_path|d(False) else (domain.name.split('.')|map('regex_replace', '^(.*)$', 'DC=\\1')|list|join(',')) }}"
        # managed_by: "{{ OU.managed_by|d()  }}"
        # domain_server: "{{ OU.serv|d(OU.domain_server|d(domain.controller|d(None))) }}"
        protected_from_accidental_deletion: "{{ OU.del|d(True) }}"
        recursive: "{{ OU.rec|d(OU.recursive|d(False)) }}"
        description: "{{ OU.descr|d('Ansible OU ' + OU.name + ' default description.') }}"
        state: "{{ 'present' if OU.present|d(True) else 'absent' }}"