---
- name: pfsense
  block:
    - name: "Delete NAT outbound traffic rule"
      pfsensible.core.nat_outbound:
        descr: 'NAT outbound traffic'
        state: absent
    - name: Create alias
      include: setAlias.yml
      loop: "{{ firewall_alias|d([]) + firewall_group_alias|d([]) + firewall_personal_alias|d([]) }}"
      loop_control:
        loop_var: alias
    - name: Create nat
      include: setNat.yml
      loop: "{{ firewall_nats|d([]) + firewall_group_nats|d([]) + firewall_personal_nats|d([]) }}"
      loop_control:
        loop_var: nat
    - name: Create rule
      include: setRule.yml
      loop: "{{ firewall_rules|d([]) + firewall_group_rules|d([]) + firewall_personal_rules|d([]) }}"
      loop_control:
        loop_var: rule
  when: ansible_facts['os_family'] == 'FreeBSD' and 'pfSense' in ansible_facts['kernel_version']
- name: Not firewall take into account
  fail:
    msg: That's kind of firewall is not configurable whrite now
  when: ansible_facts['os_family'] != 'FreeBSD' or 'pfSense' not in ansible_facts['kernel_version']