- name: Create rule '{{ rule.name }}'
  pfsensible.core.rule:
    name: "{{ rule.name }}"
    action: "{{ rule.action }}"
    interface:  "{{ rule.interface }}"
    ipprotocol: "{{ rule.ip|d('inet46') }}"
    protocol: "{{ rule.protocol|d('tcp') }}"
    source: "{{ rule.source }}"
    source_port: "{{ rule.source_port|d(None) }}"
    destination: "{{ rule.destination|d(None) }}"
    destination_port: "{{ rule.destination_port|d(None) }}"
    after: "{{ rule.position_after|d(None) }}"
    before: "{{ rule.position_before|d(None) }}"
    log: "{{ rule.log|d(True) }}"
    disabled: "{{ not rule.enabled|d(True) }}"
    state: present