- set_fact: DFS.path="C:\\DFSRoot\\{{DFS.name}}"
  when: not DFS.path|d(False)
- name: Create root share
  include: share.yml
  vars:
    share: "{{ DFS }}"
  when: DFS.path|regex_search('^[A-Z]:')
- set_fact:
    DFSfolders: "{{ DFS.childs|d([]) }}"
- include: DFSfolder.yml
- debug:
    var: DFSfolders